version: "3.9"
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: master
      DB_PASSWORD: s3cr3t
      DB_NAME: products
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: products
    ports:
      - 5432:5432
