apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: anderws10/go-products:v1.0.1
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: postgresdb-secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgresdb-secret
